@baseUrl = http://localhost:8000
@entry_id = 139f531d-636b-47b0-990f-043952dac5c6

### Create entry
POST {{baseUrl}}/entries
Content-Type: application/json

{
  "user_id": "user-1",
  "entry": "Yesterday was a productive day."
}

### Get entry
GET {{baseUrl}}/entries/{{entry_id}}

### List entries by user
GET {{baseUrl}}/entries